### ISSUE TITLE
Would like to use * wildcards in ignored files for *.png *.jpg

### ISSUE THREAD

**Issue by stevebosworth** [csaunders/themekit#36]
Might be a simple docs update or something but it would be great if we could use wildcards in our ignore files!!

**Comment by csaunders** [comment]
@stevebosworth super late response is super late, but yes you can!

It needs to be within double quotes otherwise it'll crash (I'm working on fixing that one right now).

So for example:

```yaml
development:
  store: taters.myshopify.com
  access_token: abracadabra
  ignore_files:
    - config/settings.html
    - "*.jpg"
    - "*.png"
```
